/**
 * Từ khoá tìm kiếm của từng biểu tượng: tên và từ khoá tiếng Việt của Unicode CLDR, kèm tên
 * tiếng Anh. Sinh từ dữ liệu CLDR cho đúng các biểu tượng trong `EMOJI_CATEGORIES`.
 */
export const EMOJI_KEYWORDS: Readonly<Record<string, string>> = {
  "👍": "dấu ra hiệu đồng ý | +1 | lên | ngón tay cái | tay | thumbs up",
  "❤️": "trái tim màu đỏ | cảm xúc | tình yêu | trái tim | red heart",
  "😂": "mặt cười với nước mắt vui sướng | cười | cười chảy nước mắt | hài thật | mặt | nước mắt | vui đấy | vui sướng | face with tears of joy",
  "😮": "mặt có miệng há | mặt | miệng | mở | thông cảm | face with open mouth",
  "😢": "mặt khóc | buồn | khóc | mặt | nước mắt | crying face",
  "🙏": "chắp tay | cảm ơn | cầu nguyện | hỏi | làm ơn | tay | folded hands",
  "😀": "mặt cười toe toét | cười toe toét | mặt | grinning face",
  "😃": "mặt cười miệng há với mắt to | cười | há to | mặt | mặt cười mắt mở to | miệng | grinning face with big eyes",
  "😄": "mặt cười miệng há mắt cười | cười | mắt | mặt | miệng | mở | grinning face with smiling eyes",
  "😁": "mặt cười nhe răng và mắt cười | cười | cười nhe răng và mắt cười | mắt | mặt | beaming face with smiling eyes",
  "😆": "mặt cười miệng há mắt nhắm chặt | cười | cười ngặt nghẽo | cười ngoác miệng | cười như được mùa | cười to | hài lòng | mặt | miệng | grinning squinting face",
  "😅": "mặt cười toát mồ hôi | căng thẳng | chán nản | cười nhe răng | hào hứng | lạnh | lo lắng | mặt | miệng | mỉm cười | mở | mồ hôi | grinning face with sweat",
  "🤣": "mặt cười lăn cười bò | cười | cười chảy nước mắt | cười sung sướng | lăn | mặt | sàn | rolling on the floor laughing",
  "🙂": "mặt cười mỉm | cười | mặt | slightly smiling face",
  "🙃": "mặt lộn ngược | lộn ngược | mặt | upside-down face",
  "😉": "mặt nháy mắt | mặt | nháy mắt | winking face",
  "😊": "mặt cười híp mắt | cười mỉm | đỏ mặt | hài lòng | mắt | mặt | mặt tươi cười với đôi mắt biết cười | mỉm cười | vui mừng | smiling face with smiling eyes",
  "😇": "mặt cười có hào quang | giả tưởng | hào quang | mặt | ngây thơ | thiên thần | smiling face with halo",
  "🥰": "mặt cười với 3 trái tim | phải lòng | yêu | yêu quý | smiling face with hearts",
  "😍": "mặt cười mắt hình trái tim | cười | lãng mạn | mắt | mặt | yêu | smiling face with heart-eyes",
  "🤩": "ngưỡng mộ | cười toét | mắt | mặt | ngôi sao | star-struck",
  "😘": "mặt đang hôn gió | hôn | mặt | face blowing a kiss",
  "😗": "mặt hôn | hôn | mặt | kissing face",
  "😚": "mặt hôn mắt nhắm | hôn | mắt | mặt | nhắm | kissing face with closed eyes",
  "😙": "mặt hôn mắt cười | cười | hôn | mắt | mặt | kissing face with smiling eyes",
  "😋": "mặt thưởng thức món ngon | cười | mặt | ngon | ngon tuyệt | thưởng thức | face savoring food",
  "😛": "mặt lè lưỡi | lưỡi | mặt | face with tongue",
  "😜": "mặt lè lưỡi nháy mắt | lưỡi | mắt | mặt | nháy mắt | nói đùa | winking face with tongue",
  "🤪": "mặt làm trò hề | lớn | mắt | ngốc | nhỏ | zany face",
  "😝": "mặt thè lưỡi mắt nhắm chặt | hương vị | kinh khủng | lưỡi | mắt | mặt | squinting face with tongue",
  "🤑": "mặt có tiền ở miệng | mặt | miệng | tiền | money-mouth face",
  "🤗": "mặt ôm | mặt | ôm | smiling face with open hands",
  "🤭": "mặt với tay che miệng | tay che miệng cười | xin lỗi | face with hand over mouth",
  "🤫": "mặt ra dấu suỵt | im lặng | suỵt | shushing face",
  "🤔": "mặt suy nghĩ | đang suy nghĩ | mặt | thinking face",
  "🤐": "mặt có miệng bị kéo khóa | khóa kéo | mặt | miệng | zipper-mouth face",
  "🤨": "mặt với lông mày rướn lên | hoài nghi | ngờ vực | face with raised eyebrow",
  "😐": "mặt trung lập | mặt | mặt ngây ra bất động | trung lập | neutral face",
  "😑": "mặt vô cảm | không diễn cảm | mặt | thản nhiên | vô cảm | expressionless face",
  "😶": "mặt không có miệng | ít nói | mặt | miệng | yên lặng | face without mouth",
  "😏": "mặt cười khẩy | cười khẩy | mặt | smirking face",
  "😒": "mặt buồn | buồn | không vui | mặt | unamused face",
  "🙄": "mặt có mắt đu đưa | cái gì vậy | đu đưa | không quan tâm | mắt | mặt | sao cũng được | face with rolling eyes",
  "😬": "mặt nhăn nhó | mặt | nhăn nhó | grimacing face",
  "😌": "mặt nhẹ nhõm | mặt | nhẹ nhõm | relieved face",
  "😔": "mặt trầm ngâm | mặt | thất vọng | trầm ngâm | pensive face",
  "😪": "mặt buồn ngủ | buồn | buồn ngủ | khóc | mặt | sleepy face",
  "🤤": "mặt chảy dãi | chảy dãi | mặt | drooling face",
  "😴": "mặt đang ngủ | không quan tâm | mặt | mệt mỏi | ngủ | ngủ ngoan | sao cũng được | zzz | sleeping face",
  "😷": "mặt đeo khẩu trang y tế | bác sĩ | lạnh | mặt | mặt nạ | ốm | face with medical mask",
  "🤒": "mặt có miệng ngậm nhiệt kế | mặt | mệt | nhiệt kế | ốm | face with thermometer",
  "🤕": "mặt đeo băng đầu | băng | đau | mặt | vết thương | face with head-bandage",
  "🤢": "mặt buồn nôn | buồn nôn | mặt | nôn mửa | nauseated face",
  "🤮": "mặt nôn mửa | nôn mửa | ốm | face vomiting",
  "🥵": "mặt nóng | đỏ mặt | đổ mồ hôi | nóng | sốc nhiệt | sốt | hot face",
  "🥶": "mặt lạnh | đóng băng | lạnh | lạnh cứng | mặt xanh | tê cóng | cold face",
  "🥴": "mặt choáng váng | chếnh choáng | chóng mặt | mắt đảo điên | miệng uốn lượn | say xỉn | woozy face",
  "😵": "mặt chóng mặt | chóng mặt | mặt | mệt | ốm | face with crossed-out eyes",
  "🤯": "đầu nổ tung | bị sốc | nổ | exploding head",
  "🤠": "mặt đội mũ cao bồi | cao bồi | mặt | mũ | nữ cao bồi | cowboy hat face",
  "🥳": "mặt tiệc tùng | buổi tiệc | hào hứng | lễ kỷ niệm | mũ | sinh nhật | sừng | tiệc tùng | partying face",
  "😎": "mặt cười đeo kính | kính | mặt | mặt trời | phong cách | sáng | smiling face with sunglasses",
  "🤓": "mặt mọt sách | bốn mắt | chuyên gia | đam mê | mặt | mọt sách | thông minh | nerd face",
  "🧐": "mặt với kính một mắt | giàu có | ngột ngạt | thượng lưu | face with monocle",
  "😕": "mặt bối rối | bối rối | mặt | confused face",
  "😟": "mặt lo lắng | lo lắng | mặt | worried face",
  "🙁": "mặt hơi cau mày | cau mày | mặt | slightly frowning face",
  "😯": "mặt làm thinh | choáng váng | làm thinh | mặt | ngạc nhiên | hushed face",
  "😲": "mặt kinh ngạc | hoàn toàn | kinh ngạc | mặt | sốc | astonished face",
  "😳": "mặt đỏ ửng | choáng váng | đỏ mặt | mặt | flushed face",
  "🥺": "mặt cầu xin | lòng thương | mắt cún con | xin xỏ | pleading face",
  "😦": "mặt cau miệng há | mặt | miệng | mở | nhăn mặt | frowning face with open mouth",
  "😧": "mặt đau khổ | đau khổ | mặt | anguished face",
  "😨": "mặt sợ hãi | kinh hãi | mặt | sợ | sợ hãi | fearful face",
  "😰": "mặt lo lắng và toát mồ hôi | lạnh | mặt | mặt lo lắng và toát mồ hôi mồ hôi | vội vã | xanh da trời | anxious face with sweat",
  "😥": "mặt thất vọng nhưng nhẹ nhõm | mặt | ngạc nhiên | nhẹ nhõm | thất vọng | sad but relieved face",
  "😭": "mặt khóc to | buồn | khóc | mặt | nước mắt | thổn thức | loudly crying face",
  "😱": "mặt la hét kinh hãi | kinh sợ | la hét | mặt | sợ | sợ hãi | face screaming in fear",
  "😖": "mặt xấu hổ | mặt | xấu hổ | confounded face",
  "😣": "mặt kiên nhẫn | đau đầu | kiên nhẫn | mặt | tập trung | persevering face",
  "😞": "mặt thất vọng | mặt | thất vọng | disappointed face",
  "😓": "mặt chán nản với mồ hôi | lạnh | mặt | mồ hôi | downcast face with sweat",
  "😩": "mặt kiệt sức | kiệt sức | mặt | mệt mỏi | weary face",
  "😫": "mặt mệt mỏi | mặt | mệt mỏi | tired face",
  "🥱": "mặt đang ngáp | buồn ngủ | chán | không quan tâm | mặt ngáp | mệt mỏi | ngáp | ngủ thôi | sao cũng được | yawning face",
  "😤": "mặt có mũi đang phì hơi | chiến thắng | hân hoan | không vui | mặt | tức giận | face with steam from nose",
  "😡": "mặt hờn dỗi | cơn thịnh nộ | điên | đỏ | hờn dỗi | mặt | tức giận | enraged face",
  "😠": "mặt giận giữ | điên | mặt | tức giận | angry face",
  "🤬": "mặt có các ký hiệu trên miệng | chửi rủa | chửi thề | tức giận | face with symbols on mouth",
  "😈": "mặt cười có sừng | cười | mặt | sừng | truyện cổ tích | tưởng tượng | smiling face with horns",
  "💀": "đầu lâu | cái chết | mặt | quái vật | truyện cổ tích | skull",
  "💩": "đống phân | chất thải | hài hước | khuôn mặt | phân | quái vật | pile of poo",
  "🤡": "mặt hề | hề | mặt | clown face",
  "👻": "ma | mặt | quái vật | sinh vật | truyện cổ tích | tưởng tượng | ghost",
  "👽": "người ngoài hành tinh | đĩa bay | giả tưởng | khuôn mặt | ngoài trái đất | sinh vật | alien",
  "🤖": "mặt rô-bốt | mặt | quỷ | rô-bốt | robot",
  "👎": "dấu ra hiệu từ chối | -1 | không thích | ngón tay cái | tay | xuống | thumbs down",
  "👌": "bàn tay làm dấu ok | chắc chắn rồi | được | ok | ok nha | tay | tuyệt | ok hand",
  "✌️": "tay chiến thắng | chiến thắng | chữ v | tay | v | victory hand",
  "🤞": "hai ngón tay bắt chéo | bàn tay | chéo | may mắn | ngón tay | crossed fingers",
  "🤟": "cử chỉ yêu nhau | anh yêu em | ba ngón tay | tay | love-you gesture",
  "🤘": "ký hiệu cặp sừng | ngón tay | sừng | tay | tuyệt vời | sign of the horns",
  "🤙": "bàn tay gọi cho tôi | bàn tay | gọi điện | call me hand",
  "👈": "ngón trỏ trái chỉ sang trái | chỉ | mu bàn tay | ngón tay | ngón trỏ | tay | backhand index pointing left",
  "👉": "ngón trỏ trái chỉ sang phải | chỉ | mu bàn tay | ngón tay | ngón trỏ | tay | backhand index pointing right",
  "👆": "ngón trỏ trái chỉ lên | chỉ | lên | ngón tay | tay | tay trái | backhand index pointing up",
  "👇": "ngón trỏ trái chỉ xuống | mu bàn tay | ngón tay | ngón trỏ | tay | trỏ | backhand index pointing down",
  "☝️": "ngón trỏ chỉ lên trên | chỉ | lên | ngón tay | ngón trỏ | tay | index pointing up",
  "✋": "bàn tay giơ lên | dừng lại | tay | raised hand",
  "🤚": "mu bàn tay giơ lên | giơ lên | mu bàn tay | raised back of hand",
  "🖐️": "tay xòe ngón giơ lên | dừng | ngón tay | tay | xòe | hand with fingers splayed",
  "🖖": "tay thần lửa | ngón tay | spock | tay | thần lửa | vulcan salute",
  "👋": "vẫy tay | chào | chào nhé | có ai ở đó không? | đang vẫy | tay | vẫy | vẫy tay nè | xin chào | waving hand",
  "🤝": "bắt tay | đồng ý | gặp mặt | rung | tay | handshake",
  "👏": "vỗ tay | hai bàn tay đang vỗ | tay | clapping hands",
  "🙌": "hai bàn tay giơ lên | cử chỉ | hoan hô | lễ kỷ niệm | nâng lên | tay | raising hands",
  "👐": "hai bàn tay đang xòe | mở ra | tay | open hands",
  "🤲": "hai bàn tay chạm vào nhau | cầu nguyện | lời cầu nguyện | palms up together",
  "✍️": "bàn tay đang viết | tay | viết | writing hand",
  "💪": "bắp tay gập lại | bắp tay | cơ bắp | gập lại | hài hước | flexed biceps",
  "👀": "đôi mắt | mắt | mặt | eyes",
  "🧠": "não | thông minh | brain",
  "👶": "trẻ con | trẻ em | trẻ sơ sinh | baby",
  "🧒": "trẻ em | giới tính chung | giới tính không xác định | trẻ | child",
  "👦": "con trai | cậu bé | boy",
  "👧": "con gái | bím tóc | cô gái | cung hoàng đạo | trẻ | xử nữ | girl",
  "🧑": "người | giới tính chung | giới tính không xác định | người lớn | person",
  "👨": "đàn ông | người lớn | man",
  "👩": "phụ nữ | người lớn | woman",
  "🧓": "người lớn tuổi | già | giới tính không xác định | giới tính trung lập | older person",
  "👴": "cụ ông | đàn ông | đầu hói | già | người lớn | old man",
  "👵": "cụ bà | già | người lớn | phụ nữ | old woman",
  "🙋": "người giơ cao tay | chọn tôi đi | cử chỉ | giơ tay | nâng lên | người vui vẻ giơ cao tay | ở bên này | tay | tôi có thể giúp | tôi muốn hỏi | vui vẻ | person raising hand",
  "🙆": "người ra hiệu đồng ý | cử chỉ | đồng ý | ok | tay | thể dục | person gesturing ok",
  "🙅": "người ra hiệu phản đối | cấm | cử chỉ | không bao giờ | không cho phép | không đời nào | tay | person gesturing no",
  "🤷": "người nhún vai | ai mà biết được | có thể | hững hờ | không biết | nghi ngờ | nhún vai | sao cũng được | thờ ơ | person shrugging",
  "🤦": "người lấy tay che mặt | hoài nghi | không tin nổi | lại nữa rồi | lòng bàn tay | mặt | người dùng tay che mặt | tay che mặt | tức giận | person facepalming",
  "🙇": "người đang cúi đầu | cầu xin | cử chỉ | cúi người | hối tiếc | lấy làm tiếc | lời xin lỗi | tha thứ | tội nghiệp | person bowing",
  "💁": "người ra hiệu trợ giúp | giúp | hất tóc | mách nước | mỉa mai | nghiêm túc | tay | thông tin | tươi tắn | vuốt tóc | person tipping hand",
  "👨‍🏫": "giáo viên nam | giáo sư | giáo viên | nam | người hướng dẫn | man teacher",
  "👩‍🏫": "giáo viên nữ | giáo sư | giáo viên | người hướng dẫn | phụ nữ | woman teacher",
  "👨‍🎓": "sinh viên nam | nam | sinh viên | tốt nghiệp | man student",
  "👩‍🎓": "sinh viên nữ | nữ | sinh viên | tốt nghiệp | woman student",
  "👨‍💻": "kỹ sư công nghệ nam | kỹ sư công nghệ | lập trình viên | người đàn ông | người phát minh | nhà phát triển | phần mềm | man technologist",
  "👩‍💻": "kỹ sư công nghệ nữ | kỹ sư công nghệ | lập trình viên | người phát minh | người phụ nữ | nhà phát triển | phần mềm | woman technologist",
  "🏃": "người chạy | chạy bộ | chạy đua maratông | chạy nhanh | đang đến | tốc độ | vội vã | person running",
  "🚶": "người đi bộ | dáng đi | đang đi bộ | đi bộ | đi bộ leo núi | đi lang thang | đi thong dong | tản bộ | person walking",
  "💃": "người phụ nữ đang khiêu vũ | khiêu vũ | nhảy | phụ nữ | woman dancing",
  "🕺": "người đàn ông đang khiêu vũ | khiêu vũ | người đàn ông | man dancing",
  "👪": "gia đình | trẻ em | family",
  "🧡": "trái tim màu cam | màu cam | orange heart",
  "💛": "trái tim màu vàng | cảm xúc | màu vàng | trái tim | yêu | yellow heart",
  "💚": "trái tim màu lục | màu lục | green heart",
  "💙": "trái tim màu lam | màu lam | blue heart",
  "💜": "trái tim màu tím | tím | trái tim tím | purple heart",
  "🤎": "trái tim màu nâu | màu nâu | trái tim | brown heart",
  "🖤": "trái tim màu đen | đen | điều ác | tim đen | xấu | black heart",
  "🤍": "trái tim màu trắng | màu trắng | trái tim | white heart",
  "💔": "trái tim tan vỡ | bị vỡ | buồn | cô đơn | vỡ | broken heart",
  "❣️": "dấu chấm than hình trái tim đậm | cảm thán | chấm câu | dấu | heart exclamation",
  "💕": "hai trái tim | hẹn hò | hôn | yêu | two hearts",
  "💞": "trái tim xoay vòng | đang quay | revolving hearts",
  "💓": "trái tim đang đập | dao động | đập | nhịp tim | beating heart",
  "💗": "trái tim lớn dần | bị kích thích | lo lắng | nhịp tim | phát triển | growing heart",
  "💖": "trái tim lấp lánh | bị kích thích | lấp lánh | sparkling heart",
  "💘": "trái tim với mũi tên | mũi tên | thần tình yêu | heart with arrow",
  "💝": "trái tim với ruy băng | lễ tình yêu | ruy băng | trái tim | heart with ribbon",
  "💯": "100 điểm | 100 | điểm | một trăm | toàn bộ | hundred points",
  "💢": "biểu tượng giận giữ | điên | hài hước | tức giận | anger symbol",
  "💥": "va chạm | bom | bùng nổ | hài hước | nổ | collision",
  "💫": "choáng váng | hài hước | ngôi sao | dizzy",
  "💦": "giọt mồ hôi | bắn tung tóe | giọt nước | hài hước | mồ hôi | nước | tập thể dục | sweat droplets",
  "💨": "lao đi | chạy | chớp nhoáng | hài hước | lao | dashing away",
  "🔥": "lửa | dụng cụ | ngọn lửa | fire",
  "✨": "ánh lấp lánh | kỳ diệu | lấp lánh | ngôi sao | sparkles",
  "⭐": "ngôi sao | sao | thiên văn | star",
  "🌟": "ngôi sao lấp lánh | chiếu sáng | lấp lánh | ngôi sao | phát sáng | glowing star",
  "⚡": "điện cao thế | cú đánh | điện | nguy hiểm | sét | tự nhiên | high voltage",
  "✅": "dấu chọn đậm màu trắng | ✓ | chọn | dấu | dấu tích | nút | check mark button",
  "☑️": "hộp kiểm có dấu chọn | ✓ | chọn | dấu tích | hoàn thành | hộp | check box with check",
  "✔️": "dấu chọn | ✓ | chọn | dấu | dấu kiểm | dấu tích | check mark",
  "❌": "dấu gạch chéo | dấu | hủy | nhân | x | cross mark",
  "❎": "nút dấu gạch chéo | dấu | dấu nhân | hình vuông | cross mark button",
  "❗": "dấu chấm than đỏ | ! | cảm thán | chấm | chấm than | dấu | dấu chấm than | red exclamation mark",
  "❓": "dấu chấm hỏi | chấm câu | dấu | hỏi | red question mark",
  "‼️": "hai dấu chấm than | chấm câu | chấm than | dấu | double exclamation mark",
  "⁉️": "dấu chấm than và dấu chấm hỏi | chấm câu | chấm hỏi | chấm than | dấu | exclamation question mark",
  "⚠️": "cảnh báo | thận trọng | warning",
  "🚫": "bị cấm | cấm | không | không có | lối vào | prohibited",
  "⛔": "cấm vào | cấm | giao thông | không cho phép | lối vào | no entry",
  "🆗": "nút ok | ok | ok button",
  "🆕": "nút new | mới | new | new button",
  "🆒": "nút cool | cool | mát | cool button",
  "🆙": "nút up! | dấu | up | up! button",
  "🔔": "cái chuông | giờ nghỉ | nhà thờ | bell",
  "🔕": "chuông với dấu gạch chéo | cấm | chuông | im lặng | tắt tiếng | bell with slash",
  "➕": "cộng | + | dấu | toán | plus",
  "➖": "trừ | - | − | dấu | toán | minus",
  "✖️": "dấu nhân | × | dấu | hủy | nhân | x | multiply",
  "➗": "dấu chia | ÷ | chia | dấu | toán | divide",
  "🔴": "hình tròn màu đỏ | đỏ | hình học | hình tròn | red circle",
  "🟠": "hình tròn màu cam | da cam | hình tròn | màu cam | vòng tròn | orange circle",
  "🟡": "hình tròn màu vàng | hình tròn | màu vàng | vòng tròn | yellow circle",
  "🟢": "hình tròn màu xanh lá cây | hình tròn | màu xanh lá cây | vòng tròn | xanh lá | xanh lục | green circle",
  "🔵": "hình tròn màu lam | hình học | hình tròn | màu lam | blue circle",
  "🟣": "hình tròn màu tím | hình tròn | màu tím | tía | vòng tròn | purple circle",
  "⚫": "hình tròn màu đen | hình học | hình tròn | black circle",
  "⚪": "hình tròn màu trắng | hình học | hình tròn | white circle",
  "🐶": "mặt cún | cún | động vật | mặt | thú cưng | dog face",
  "🐱": "mặt mèo | động vật | mặt | mèo | thú cưng | cat face",
  "🐭": "mặt chuột | chuột | động vật | mặt | mouse face",
  "🐹": "mặt hamster | chuột hamster | mặt | thú cưng | hamster",
  "🐰": "mặt thỏ | con thỏ | động vật | mặt | thỏ | thú cưng | rabbit face",
  "🦊": "cáo | động vật | mặt | fox",
  "🐻": "gấu | động vật | gầm | gấu xám | mặt | mật ong | bear",
  "🐼": "mặt gấu trúc | gấu trúc | mặt | panda",
  "🐨": "gấu túi | con gấu | động vật | koala | úc",
  "🐯": "mặt hổ | dã thú | động vật | hổ | mặt | tiger face",
  "🦁": "sư tử | cung hoàng đạo | cung sư tử | mặt | mặt sư tử | lion",
  "🐮": "mặt bò | bò | bò cái | động vật | mặt | sữa | trang trại | cow face",
  "🐷": "mặt lợn | động vật | lợn | thịt lợn | thịt xông khói | trang trại | pig face",
  "🐸": "ếch | mặt | frog",
  "🐵": "mặt khỉ | động vật | khỉ | khuôn mặt | quả chuối | monkey face",
  "🙈": "khỉ không nhìn điều xấu | cấm | điều xấu | khỉ | mặt | nhìn | see-no-evil monkey",
  "🙉": "khỉ không nghe điều xấu | cấm | điều xấu | khỉ | mặt | nghe | hear-no-evil monkey",
  "🙊": "khỉ không nói điều xấu | cấm | điều xấu | khỉ | mặt | nói | speak-no-evil monkey",
  "🐔": "gà | chim | động vật | chicken",
  "🐧": "chim cánh cụt | chim | động vật | nam cực | penguin",
  "🐦": "chim | động vật | bird",
  "🐤": "gà con | chim | gà | baby chick",
  "🦆": "vịt | chim | động vật | duck",
  "🦉": "cú | chim | động vật | khôn ngoan | owl",
  "🐝": "ong mật | con ong | côn trùng | động vật | mùa xuân | honeybee",
  "🦋": "bướm | côn trùng | đẹp | butterfly",
  "🐌": "ốc sên | động vật | thiên nhiên | vườn | snail",
  "🐞": "bọ rùa | bọ cánh cứng | con bọ rùa | côn trùng | thiên nhiên | lady beetle",
  "🐢": "rùa | con rùa | động vật | rùa nước ngọt | turtle",
  "🐍": "rắn | chòm sao xà phu | cung hoàng đạo | động vật | vật mang | snake",
  "🐙": "bạch tuộc | đại dương | động vật | sinh vật | octopus",
  "🐬": "cá heo | bãi biển | chân chèo | đại dương | động vật | dolphin",
  "🐳": "cá voi đang phun nước | bãi biển | cá voi | đại dương | động vật | khuôn mặt | phun nước | spouting whale",
  "🐟": "cá | cung hoàng đạo | cung song ngư | fish",
  "🦈": "cá mập | cá | động vật | shark",
  "🌸": "hoa anh đào | hoa | thực vật | cherry blossom",
  "🌹": "hoa hồng | cây | hoa | màu đỏ | sang trọng | tình yêu | valentine | vẻ đẹp | rose",
  "🌺": "hoa dâm bụt | hoa | thực vật | hibiscus",
  "🌻": "hoa hướng dương | hoa | mặt trời | thực vật | sunflower",
  "🌼": "hoa | bồ công anh | thực vật | blossom",
  "🌷": "hoa tulip | hoa | thực vật | tulip",
  "🌱": "cây non | cây giống | nảy mầm | non | thực vật | seedling",
  "🌿": "thảo mộc | lá cây | herb",
  "🍀": "cỏ bốn lá | 4 | bốn | lá cây | thực vật | four leaf clover",
  "🍁": "lá phong | lá cây | rụng | maple leaf",
  "🍂": "lá rụng | lá | rụng | thực vật | fallen leaf",
  "🌳": "cây rụng lá | cây | rơi | rụng lá | deciduous tree",
  "🌵": "cây xương rồng | hạn hán | sa mạc | thiên nhiên | thực vật | cactus",
  "🌈": "cầu vồng | chuyển giới | đồng tính | lưỡng tính | mưa | thời tiết | tự nhiên | rainbow",
  "☀️": "mặt trời | nắng | nóng | sáng | thời tiết | tia | sun",
  "⛅": "mặt trời sau đám mây | mặt trời | mây | sun behind cloud",
  "🌧️": "mây và mưa | mây | mưa | cloud with rain",
  "⛈️": "đám mây kèm chớp và mưa | đám mây với tia chớp và mưa | mây | mưa | sấm | cloud with lightning and rain",
  "❄️": "bông tuyết | lạnh | thời tiết | tuyết | snowflake",
  "☃️": "người tuyết | lạnh | tuyết | snowman",
  "🌙": "trăng lưỡi liềm | lưỡi liềm | mặt trăng | crescent moon",
  "🌏": "địa cầu thể hiện châu á-châu úc | châu á | châu á-châu úc | châu úc | địa cầu | thế giới | thể hiện | trái đất | globe showing asia-australia",
  "🍎": "táo đỏ | đỏ | hoa quả | táo | red apple",
  "🍊": "quýt | hoa quả | quả cam | tangerine",
  "🍋": "chanh tây | chanh | chua | họ cam quýt | hoa quả | lemon",
  "🍌": "chuối | hoa quả | kali | banana",
  "🍉": "dưa hấu | hoa quả | watermelon",
  "🍇": "chùm nho | hoa quả | nho | grapes",
  "🍓": "dâu tây | quả mọng | trái cây | strawberry",
  "🍒": "anh đào | hoa quả | màu đỏ | quả mọng | thực vật | trái cây | cherries",
  "🍑": "đào | hoa quả | peach",
  "🥭": "xoài | nhiệt đới | trái cây | mango",
  "🍍": "dứa | hoa quả | nhiệt đới | pineapple",
  "🥥": "dừa | cây dừa | pina colada | coconut",
  "🥑": "quả bơ | hoa quả | thức ăn | avocado",
  "🍅": "cà chua | rau | thực vật | tomato",
  "🌽": "bắp ngô | bắp | ngô | ear of corn",
  "🥕": "cà rốt | thức ăn | thực vật | carrot",
  "🥦": "xúp lơ xanh | bông cải xanh | cải bắp dại | hoa lơ | broccoli",
  "🍞": "bánh mì | bánh mì nướng | lúa mì | ngũ cốc | nhà hàng | ổ bánh mì | thực phẩm | tinh bột | bread",
  "🧀": "miếng pho mát | phô mai | cheese wedge",
  "🍳": "nấu ăn | cái chảo | chiên | trứng | cooking",
  "🍔": "bánh hamburger | bánh kẹp | hamburger",
  "🍟": "khoai tây chiên | đồ ăn | đồ ăn nhanh | kiểu pháp | french fries",
  "🍕": "bánh pizza | lát | phô mai | pizza",
  "🌭": "bánh mì xúc xích | xúc xích | hot dog",
  "🥪": "bánh mỳ kẹp | bánh mỳ | sandwich",
  "🌮": "bánh taco | bánh mexico | taco",
  "🍜": "bát mì | bát | đũa | mỳ | mỳ ramen | nóng hổi | phở | súp | thức ăn | steaming bowl",
  "🍲": "nồi thức ăn | hầm | nồi | súp | pot of food",
  "🍛": "cơm cà ri | cà ri | cơm | curry rice",
  "🍣": "sushi | thực phẩm",
  "🍱": "hộp cơm bento | cơm bento | hộp | bento box",
  "🥟": "bánh bao | sủi cảo | dumpling",
  "🍤": "tôm chiên | chiên | món sốt cá cua tôm | tôm | tôm hùm | fried shrimp",
  "🍙": "cơm nắm | cơm | nhật bản | rice ball",
  "🍚": "cơm | gạo | nấu chín | cooked rice",
  "🍰": "bánh ngọt | bánh | miếng | món tráng miệng | ngọt | shortcake",
  "🎂": "bánh sinh nhật | bánh | lễ kỷ niệm | món tráng miệng | ngọt | sinh nhật | tráng miệng | birthday cake",
  "🧁": "bánh nướng nhỏ | bánh ngọt | ngọt | tiệm bánh | tráng miệng | cupcake",
  "🍩": "bánh rán vòng | món tráng miệng | ngọt | doughnut",
  "🍪": "bánh quy | món tráng miệng | ngọt | cookie",
  "🍫": "thanh sô cô la | món tráng miệng | ngọt | sô cô la | thanh | chocolate bar",
  "🍬": "kẹo | món tráng miệng | ngọt | candy",
  "🍭": "kẹo mút | kẹo | món tráng miệng | ngọt | lollipop",
  "🍦": "kem mềm | cái kem | kem | mềm | món tráng miệng | ngọt | soft ice cream",
  "☕": "đồ uống nóng | buổi sáng | cà phê | caffeine | chai | đồ uống | nóng | nóng hổi | trà | hot beverage",
  "🍵": "tách trà không có quai | cốc | đồ uống | tách trà | trà | uống | teacup without handle",
  "🥤": "cốc và ống hút | cốc | mạch nha | nước | nước ép | ống hút | soda | uống | cup with straw",
  "🧃": "hộp đồ uống | đồ uống | hộp | ngọt | nước ép | ống hút | beverage box",
  "🍺": "cốc bia | bia | cốc | đồ uống | quán bar | beer mug",
  "🍻": "chạm cốc bia | bia | chạm cốc | đồ uống | nước giải khát | quán ba | clinking beer mugs",
  "🥂": "chạm cốc | chúc mừng | cốc | đồ uống | tiếng keng | clinking glasses",
  "🍷": "ly rượu vang | đồ uống | ly | quán ba | rượu | uống | wine glass",
  "🎉": "pháo giấy buổi tiệc | buổi tiệc | lễ kỷ niệm | pháo bông sinh nhật | party popper",
  "🎊": "bóng hoa giấy | bữa tiệc | lễ kỷ niệm | quả bóng | confetti ball",
  "🎈": "bóng bay | lễ kỷ niệm | sinh nhật | balloon",
  "🎁": "gói quà | hộp | lễ kỷ niệm | quà | quà tặng | wrapped gift",
  "🎀": "ruy băng | lễ kỷ niệm | ribbon",
  "🏆": "cúp | chiến thắng | giải thưởng | thể thao | vô địch | trophy",
  "🥇": "huy chương vàng | huy chương | nhất | vàng | 1st place medal",
  "🥈": "huy chương bạc | bạc | hai | huy chương | 2nd place medal",
  "🥉": "huy chương đồng | ba | đồng | huy chương | 3rd place medal",
  "🏅": "huy chương thể thao | chiến thắng | huy chương | huy chương vàng | vô địch | sports medal",
  "🎖️": "huân chương quân đội | huy chương | lễ kỷ niệm | quân sự | military medal",
  "⚽": "bóng đá | quả bóng | thể thao | thể thao vua | túc cầu | soccer ball",
  "🏀": "bóng rổ | quả bóng | thể thao | vòng | basketball",
  "🏐": "bóng chuyền | quả bóng | trò chơi | volleyball",
  "🏸": "cầu lông | kỹ thuật ghi | trái cầu lông | trò chơi | vợt | badminton",
  "🏓": "bóng bàn | gậy | quả bóng | trò chơi | vợt đánh bóng | ping pong",
  "🎾": "quần vợt | cái vợt | quả bóng | tennis",
  "🏊": "người bơi | ba môn phối hợp | bơi | bơi tự do | người đàn ông bơi lội | thể thao | vận động viên bơi lội | person swimming",
  "🚴": "người đi xe đạp | đạp xe | người đạp xe | thể thao | vận động viên đua xe đạp | xe đạp | person biking",
  "🎮": "trò chơi điện tử | giải trí | tay điều khiển | thiết bị điều khiển | trò chơi | video game",
  "🎲": "trò xúc xắc | con xúc xắc | gieo xúc xắc | trò chơi | xúc xắc | game die",
  "🧩": "ghép hình | đầu mối | ghép vào nhau | mảnh | trò ghép hình | puzzle piece",
  "🎯": "trúng đích | hồng tâm | mục tiêu | phi tiêu | trò chơi | bullseye",
  "🎨": "bảng màu | bảo tàng | nghệ thuật | vẽ | artist palette",
  "🎵": "nốt nhạc | nhạc | musical note",
  "🎶": "các nốt nhạc | nhạc | nốt nhạc | musical notes",
  "🎤": "micrô | âm thanh | hát | karaoke | nhạc | microphone",
  "🎧": "tai nghe | âm thanh | headphone",
  "🎬": "bảng clapper | diễn | phim | clapper board",
  "📚": "sách | đọc | học tập | thư viện | tri thức | trường học | books",
  "📖": "sách đang mở | mở | sách | open book",
  "📝": "sổ ghi nhớ | bút chì | memo",
  "✏️": "bút chì | văn phòng phẩm | pencil",
  "🖊️": "bút | bút bi | pen",
  "📐": "thước tam giác | bộ | tam giác | thước kẻ | triangular ruler",
  "📏": "thước thẳng | cạnh thẳng | thước kẻ | toán | straight ruler",
  "🧮": "bàn tính | tính toán | abacus",
  "🔬": "kính hiển vi | dụng cụ | khoa học | kính hiển vị | thí nghiệm | microscope",
  "🧪": "ống nghiệm | hóa học | khoa học | nhà hóa học | phòng thí nghiệm | thí nghiệm | test tube",
  "🎓": "mũ tốt nghiệp | cái mũ | lễ kỷ niệm | quần áo | tốt nghiệp | graduation cap",
  "🏫": "trường học | tòa nhà | school",
  "💡": "bóng đèn | ánh sáng | điện | hài hước | ý tưởng | light bulb",
  "📌": "đinh ghim | cái ghim | pushpin",
  "📎": "kẹp giấy | paperclip",
  "📅": "lịch | ngày | calendar",
  "📆": "quyển lịch bloc | lịch | tear-off calendar",
  "🗓️": "lịch gáy xoắn | gáy xoắn | lịch | spiral calendar",
  "⏰": "đồng hồ báo thức | báo thức | đồng hồ | muộn | thời gian | alarm clock",
  "⏱️": "đồng hồ bấm giờ | đồng hồ | thời gian | stopwatch",
  "⌛": "đồng hồ cát đã chảy hết | bộ định thời | cát | đồng hồ cát | đồng hồ hẹn giờ | hourglass done",
  "⏳": "đồng hồ cát đang chảy | bộ định thời | cát | đồng hồ cát | hourglass not done",
  "📱": "điện thoại di động | di động | điện thoại | mobile phone",
  "💻": "máy tính xách tay | cá nhân | máy tính | pc | laptop",
  "🖥️": "máy tính để bàn | màn hình | máy tính | desktop computer",
  "⌨️": "bàn phím | máy tính | keyboard",
  "🖨️": "máy in | máy tính | printer",
  "📷": "máy ảnh | video | camera",
  "📞": "ống nghe điện thoại bàn | điện thoại | ống nghe | telephone receiver",
  "✉️": "phong bì | email | thư | envelope",
  "📧": "email | thư | e-mail",
  "📨": "phong bì thư đến | email | nhận | phong bì | thư | thư đến | incoming envelope",
  "📦": "gói | bưu kiện | hộp | package",
  "📋": "bảng ghi nhớ | ghi chú | việc cần làm | clipboard",
  "📁": "thư mục tệp | tệp | thư mục | file folder",
  "📂": "thư mục tệp mở | mở | tệp | thư mục | open file folder",
  "🗂️": "dụng cụ chia chỉ mục thẻ | chỉ mục | dụng cụ chia | thẻ | card index dividers",
  "📊": "biểu đồ thanh | biểu đồ | đồ thị | thanh | bar chart",
  "📈": "biểu đồ tăng | biểu đồ | đồ thị | tăng lên | tăng trưởng | xu hướng | chart increasing",
  "📉": "biểu đồ giảm | biểu đồ | đồ thị | xu hướng | xuống | chart decreasing",
  "🔍": "kính phóng đại nghiêng sang trái | dụng cụ | kính | phóng đại | tìm kiếm | magnifying glass tilted left",
  "🔑": "chìa khóa | khóa | mật khẩu | key",
  "🔒": "khóa | đóng | riêng tư | locked",
  "🔓": "mở khóa | khóa | mở | unlocked",
  "🔧": "cờ lê | chìa vặn | dụng cụ | wrench",
  "🛠️": "búa và cờ lê | búa | chìa vặn | cờ lê | dụng cụ | hammer and wrench",
  "💰": "túi tiền | đô la | tiền | túi | money bag",
  "💵": "tiền giấy đô la | đô la | hoá đơn | tiền | tiền giấy | tiền tệ | dollar banknote",
  "💳": "thẻ tín dụng | ngân hàng | thanh toán | thẻ | tiền | tín dụng | credit card",
  "🧾": "biên nhận | chứng từ | ghi sổ sách | giấy tờ chứng thực | hóa đơn | kế toán | receipt",
  "🎒": "ba lô đi học | cặp | trường | túi | backpack",
  "🚗": "ô tô | xe cộ | automobile",
  "🚌": "xe buýt | trường học | xe cộ | bus",
  "✈️": "máy bay | bay | di chuyển | phi cơ | tàu bay | airplane",
  "🚀": "tên lửa | di chuyển | không gian | phóng | rocket",
  "🏠": "ngôi nhà | nhà | house",
  "🏢": "tòa nhà văn phòng | công việc | dạng lập phương | thành phố | tòa nhà | văn phòng | office building",
};
